apiVersion: v2
publisher: cdr
name: eclipse
version: latest
type: Che Editor
displayName: Eclipse IDE
title: Eclipse IDE (in browser using Broadway) as editor for Eclipse Che
description: Eclipse running on the Web with Broadway
category: Editor
repository: 'https://github.com/ws-skeleton/che-editor-eclipseide/'
spec:  
  endpoints:
    - name: eclipse-ide
      targetPort: 5000      
      attributes:
        type: ide
        protocol: http
      public: true
  containers:
    - image: 'wsskeleton/eclipse-broadway:latest'
      mountSources: true
      memoryLimit: 2048M
      volumes:
        - name: user-data
          mountPath: /home/coder/.local/share/code-server
      name: code-server
      ports:
        - exposedPort: 5000
  initContainers: []
